### ISSUE TITLE
Ledger app for different BIPs

### ISSUE THREAD

**Issue by Akuukis** [lenondupe/ledger-app-stellar#11]
As far I know each Network should have its own BIP. Unfortunely, [here](https://github.com/LedgerHQ/ledgerjs/blob/master/packages/hw-app-str/src/utils.js#L107-L115) in Ledger app I found hardcoded Stellar Public Network BIP. Anyway, if I remove that check and try with latest ledger-app-stellar v2.1.0 on Ledger Manager, it would throw the following error for non-148 BIPs.

```
{ Error
  name: 'TransportStatusError',
  message: 'Ledger device: UNKNOWN_ERROR (0x6804)',
  stack: ...,
  statusCode: 26628,
  statusText: 'UNKNOWN_ERROR' }
```

From your release notes I understand, that Ledger app is Stellar Public Network agnostic and is looking forward to handle any network that uses Stellar Technology. At [FIC Network](ficnetwork.com) we also use Stellar technology, but are creating our own network. It would be great to have a single app for both and other upcoming Stellar-based networks.

I have few questions:
1. Perhaps non-hardcoded BIPs are already solved with ledger-app-stellar v3.0.0?
2. If not, what's the best way forward - add such feature and use one app, or create multiple apps each with its own hardcoded BIP, or something else?
3. Does this ticket belongs here or at [LedgerHQ/ledgerjs](https://github.com/LedgerHQ/ledgerjs/issues)?

**Comment by lenondupe** [comment]
In theory it is possible but it requires more than a change to the LedgerJS library. When Ledger apps are loaded onto the device they are locked on a BIP32 path to ensure they can't access other apps keys (security measure). See the APP_LOAD_PARAMS in the [Makefile](https://github.com/lenondupe/ledger-app-stellar/blob/master/Makefile#L24). So in order to have your own coin type for FIC Network you'd have to convince Ledger to build and install you a dedicated version of the app (also with different icons and maybe some change to detect the network and display the native currency).

**Comment by Akuukis** [comment]
@lenondupe Thanks for info. We will move forward to make our own application and talk to Ledger then.
