### ISSUE TITLE
v3 is not compatible with stellar account viewer

### ISSUE THREAD

**Issue by Tommixoft** [lenondupe/ledger-app-stellar#15]
Hi i bet you know this problem. But i no longer can use stellar account viewer or stellarterm or any other.
How to make it work? use Opera, Chrome, reinstalled and installed app did everything -still doesn't detect my ledger in websites,
Do you even test before deploying updates? You locked away me from my tokens. Really, how to get older version?

**Comment by lenondupe** [comment]
I'm aware some people are experiencing problems. But it seems the majority are not. Of course I tested it before updating what kind of question is that? Please keep your emotions in check when talking to people. You will find they are much more willing to help you if you approach them in a civilized manner.

We don't yet know the cause of why people are experiencing this problem. But people eventually get it to work by trying a number of things.

My prime suspect is the browser cache. The new version requires an updated client-side library. If the application is still using the old library you will have this problem. In order to make sure you have the latest client library the following actions can help:

- A hard refresh of the account-viewer page: Mac: Command+Shift+R; Windows: Ctrl+F5
- Loading the application in an incognito window
- Emptying the browser cache

If nothing else helps people have reported that when they tried on another computer it worked.

**Comment by Tommixoft** [comment]
Ok now im not so emotional :) It worked on other pc. The one that did not work was win7. on win10 works with the same version browser. Did not refresh cache on win10 and worked. On win7 deleted cache 10 times, developer tools showed 0 bytes used of cache - did not help.
So 2 identical browsers and versions - win10 works, win7 doesnt. Both dont have antivirus.

**Comment by Tommixoft** [comment]
Maybe not browser's problem but ledger itself keeps something on pc? ledger drivers maybe use some tmp data and stores on pc and so on..dont know..

**Comment by lenondupe** [comment]
Might be something wrong with the physical USB connection. For instance the cable or the port itself. I've had some problem with that before and fiddling with the cable and the plug did help that time.

However I just talked to the maintainer of the account-viewer and he was also experiencing problems all of a sudden. He updated the account-viewer application to the latest version of the client library just now and then it started working for him again. Could be related or could be something random. Can try on your win7 box once more with a fresh cache? I'd like to know whether this last change indeed fixed the problem.

**Comment by Tommixoft** [comment]
I did try 1minute ago, i even cleared WHOLE browser's cache not just website. I also used incognito mode - did not help. i disabled firewall. I looked is my User account control (windows stuff) is disabled and it is. I also used NEWLY created windows account - did not help. I used 2 different USB ports on pc. Pc pretty new. I used the same cable to my Windows10 (working one) and it works, cable brand new and high quality :) Im developer myself so not very dumb at such stuff, but yeah... this problem really strange. Looks like in win7 ledger do not transmit it's state.. i think its driver's problem if users with win7 having problems... i will try to uninstall ledger drivers and reinstall.

**Comment by Tommixoft** [comment]
Couldn't find which device is ledger so failed to try to uninstalling ledger usb drivers..
I think when it works - it works. I doubt it's browser problem. I do understand that everything is javascript based, but.. cache is cleared so it had to download newest version it did not help.
Also i see 4 Angular errors, but i see it on both machines so i quess not related to problem.

**Comment by lenondupe** [comment]
Yeah the angular errors are unrelated. Thanks for testing it out. There are no native ledger drivers. Communication is on top of some generic protocol. Unfortunately more evidence this is not a straightforward problem.

**Comment by Tommixoft** [comment]
yes i see now, sorry for bad reaction :) just sad when you cant access your money with any wallet :)

**Comment by lenondupe** [comment]
Seems to have been a driver issue on Windows 7. People reporting updating the USB drivers resolves the issue. https://www.reddit.com/r/ledgerwallet/comments/98mfqm/cannot_access_my_stellar_wallet/
