### ISSUE TITLE
Wrong hash displayed when signing a transaction

### ISSUE THREAD

**Issue by bartekn** [lenondupe/ledger-app-stellar#9]
Something is probably wrong in a code calculating a hash of the transaction. Currently the Stellar Ledger app displays a prefix and suffix of the transaction hash. The prefix is correct, however suffix does not match the suffix of the hash. It's easy to reproduce using [Laboratory](https://www.stellar.org/laboratory/).

**Comment by lenondupe** [comment]
Yes, it's a known problem with the currently released version unfortunately. The display code assumes the hash is 64 bytes long instead of 32, so the second part displays the wrong bytes. It's already been fixed in the code. Although the hash signing function has also been removed. The hash is still displayed for hash-type memo. The new version will be released very soon.
